version: '2'

networks:
  internal:
  docker0:
    external:
      name: docker0

services:
  ldap-auth:
    image: linuxserver/ldap-auth:latest
    container_name: ldap-auth
    networks:
      - internal
      - docker0
    environment:
      - TZ=Europe/Moscow
    expose:
      - 8888
      - 9000
    restart: unless-stopped

  nginx-proxy:
    depends_on:
      - ldap-auth
    networks:
      - internal
      - docker0
    restart: always
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./local-config:/etc/nginx/conf.d
      - ./nginx.tmpl:/app/nginx.tmpl
      # Hack.
      - ./openssl.cnf:/etc/ssl/openssl.cnf
    environment:
      - DEFAULT_HOST=NAS.cloudns.cc
      - LDAP_BACKEND=ldap-auth
      #- LDAP_LOGIN_PORT=9000
      - LDAP_HOST=ldap://172.21.0.1:389
      #- LDAP_METHOD=start_tls
      - LDAP_METHOD=plain
      - LDAP_UID=uid
      - LDAP_PASS=<CHANGEME LDAPPASSWOD>
      - LDAP_BASE=ou=users,dc=nas,dc=nas
      - LDAP_BIND_DN=cn=readonly,dc=nas,dc=nas
      - LDAP_USER_FILTER=(uid=%(username)s)
      #- LDAP_USE_LOGIN_PAGE=true

    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt-dns:
    image: adferrand/letsencrypt-dns
    restart: always
    volumes:
      - ./certs/letsencrypt:/etc/letsencrypt
    environment:
      - "LETSENCRYPT_USER_MAIL=mail@mail.ru"
      - "LEXICON_OPTIONS=--delegated NAS.cloudns.cc"
      - "LEXICON_PROVIDER=cloudns"
      - "LEXICON_PROVIDER_OPTIONS=--auth-id=ID --auth-password=PASSWORD"

