version: '3.4'

# Base: https://github.com/sebgl/htpc-download-box

networks:
  internal:
  docker0:
    external:
      name: docker0

services:
  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    restart: unless-stopped
    networks:
      - docker0
    expose:
      - 5076
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    environment:
#      - RUN_OPTS=<run options here> #optional
      - VIRTUAL_HOST=ds-hydra2.*
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=5076
      - CERT_NAME=${CERT_NAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPS_CONFIG}/hydra2/:/config
      - ${ROOT}/downloads/complete:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    networks:
      - docker0
    expose:
      - 9117
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
#      - RUN_OPTS=<run options here> #optional
      - VIRTUAL_HOST=ds-jackett.*
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=9117
      - CERT_NAME=${CERT_NAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPS_CONFIG}/jackett/:/config
      - ${ROOT}/downloads/torrent-files:/downloads # place where to put .torrent files for manual download

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    networks:
      - docker0
    expose:
      - 8686
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - VIRTUAL_HOST=ds-lidarr.*
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=8686
      - CERT_NAME=${CERT_NAME}
      - LDAP_EXT_AUTH=${LDAP_EXT_AUTH}
      - LDAP_EXT_ADD_GROUPS=${LDAP_EXT_ADD_GROUPS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPS_CONFIG}/lidarr:/config # config files
      - ${ROOT}/downloads/complete:/downloads # download folder
      - ${ROOT}/music/Music:/music # music folder
      - ${ROOT}/videos/Clips:/movies # movies folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - docker0
    expose:
      - 7878
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - VIRTUAL_HOST=ds-radarr.*
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=7878
      - CERT_NAME=${CERT_NAME}
      - LDAP_EXT_AUTH=${LDAP_EXT_AUTH}
      - LDAP_EXT_ADD_GROUPS=${LDAP_EXT_ADD_GROUPS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPS_CONFIG}/radarr:/config # config files
      - ${ROOT}/downloads/complete:/downloads # download folder
      - ${ROOT}/videos/Films:/movies # movies folder

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - docker0
    expose:
      - 8989
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - VIRTUAL_HOST=ds-sonarr.*
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=8989
      - CERT_NAME=${CERT_NAME}
      - LDAP_EXT_AUTH=${LDAP_EXT_AUTH}
      - LDAP_EXT_ADD_GROUPS=${LDAP_EXT_ADD_GROUPS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPS_CONFIG}/sonarr:/config # config files
      - ${ROOT}/downloads/complete/:/downloads # download folder
      - /tank1/user_data/videos/TV:/tv # tv shows folder

