version: '2'

networks:
  internal:
  docker0:
    external:
      name: docker0
    
services:
  pyload:
    image: linuxserver/pyload
    restart: always
    expose:
      - 8000
    volumes:
      - /tank0/apps/pyload:/config:rw
      - /tank0/user_data/downloads:/downloads:rw
    networks:
      - internal
      - docker0
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=download-files.*
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=8000
      - CERT_NAME=NAS.cloudns.cc
      - LDAP_EXT_AUTH=true
      - LDAP_EXT_ADD_GROUPS=(memberOf=cn=users_cloud,ou=groups,dc=nas,dc=nas)

