version: '2'

networks:
  docker0:
    external:
      name: docker0
  internal:

services:
  sonerezh-db:
    image: mariadb
    restart: always
    networks:
      - internal
    volumes:
      - /tank0/apps/media/sonerezsh/data:/var/lib/mysql
    environment:
      - MYSQL_USER=sonerezh
      - MYSQL_PASSWORD=changemetoo
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=sonerezh

  sonerezh-app:
    image: sonerezh/sonerezh:latest
    restart: always
    networks:
      - internal
      - docker0
    expose:
      - 80
    depends_on:
      - sonerezh-db
    links:
      - sonerezh-db:sonerezh-db
    volumes:
      - /tank0/apps/media/sonerezsh/thumbnails:/thumbnails
      - /tank0/user_data/music/Music:/music
    env_file:
      - ./env
    environment:
      - SONEREZH_DB_PORT_3306_TCP_ADDR=sonerezh-db
      - SONEREZH_DB_ENV_MYSQL_DATABASE=sonerezh
      - SONEREZH_DB_ENV_MYSQL_USER=sonerezh
      - SONEREZH_DB_ENV_MYSQL_PASSWORD=changemetoo
      - VIRTUAL_HOST=media.*
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

   
