# https://github.com/sameersbn/docker-gitlab

version: '2.3'

networks:
  gitlab:
  docker0:
    external:
      name: docker0

services:
  redis:
    restart: always
    image: redis:6.2
    command:
      - --loglevel warning
    networks:
      - gitlab
    volumes:
      - /tank0/apps/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:11-20200524  # sameersbn/postgresql:12-20200524
    volumes:
      - /tank0/apps/gitlab/postgresql:/var/lib/postgresql:Z
    networks:
      - gitlab
    environment:
      - DB_USER=gitlab
      - DB_PASS=<DB_PASSWORD>
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm,btree_gist

  plantuml:
    restart: always
    image: plantuml/plantuml-server:jetty
    expose:
      - 8080
    networks:
      - docker0
    environment:
      # Huge diagrams.
      - PLANTUML_LIMIT_SIZE=8192
      - VIRTUAL_HOST=uml.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

  gitlab:
    restart: always
    image: sameersbn/gitlab:14.0.2
    depends_on:
      - redis
      - postgresql
      - plantuml
    ports:
      #- "11443:443"
      - "11022:22"
    expose:
      - 443
      - 80
      - 22
    volumes:
      - /tank0/repos:/home/git/data/repositories:Z
      - /tank0/repos/system/backup:/home/git/data/backups:Z
      - /tank0/repos/system/builds:/home/git/data/builds:Z
      - /tank0/repos/system/lfs-objects:/home/git/data/shared/lfs-objects:Z
      - /tank0/repos/system/public:/uploads/-/system:Z
      - /tank0/apps/gitlab/logs:/var/log/gitlab
      - /tank0/apps/gitlab/gitlab:/home/git/data:Z
      # Iframe fix.
      # - ./gitlab-nginx:/etc/nginx/sites-enabled/gitlab
      - /tank0/apps/docker-registry/certs:/docker-registry-certs

    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    networks:
      - gitlab
      - docker0
    environment:
      - VIRTUAL_HOST=git.*,gitlab.*
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
      - CERT_NAME=NAS.cloudns.cc
      - DEBUG=false

      # Default: 1
      - NGINX_WORKERS=2
      # Default: 3
      - PUMA_WORKERS=3
      # Default: 25
      - SIDEKIQ_CONCURRENCY=10

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=<DB_PASSWORD>
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - TZ=Europe/Moscow
      - GITLAB_TIMEZONE=Moscow

      - GITLAB_HTTPS=true
      - SSL_SELF_SIGNED=true
      #- SSL_VERIFY_CLIENT=true
      - NGINX_HSTS_MAXAGE=2592000

      - GITLAB_HOST=git.NAS.cloudns.cc
      #- GITLAB_PORT=11443
      - GITLAB_SSH_PORT=11022
      - GITLAB_RELATIVE_URL_ROOT=
      - GITLAB_SECRETS_DB_KEY_BASE=<DB_KEY_BASE>
      - GITLAB_SECRETS_SECRET_KEY_BASE=<SECRET_KEY_BASE>
      - GITLAB_SECRETS_OTP_KEY_BASE=<OTP_KEY_BASE>
      - GITLAB_SIGNUP_ENABLED=false

      # Defaults to 5iveL!fe.
      - GITLAB_ROOT_PASSWORD=
      - GITLAB_ROOT_EMAIL=<gitlab_root@yandex.ru>
      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_INCOMING_EMAIL_ENABLED=false
      - GITLAB_EMAIL=<yourmail@yandex.ru>
      - GITLAB_EMAIL_REPLY_TO=noreply@yandex.ru
      - GITLAB_INCOMING_EMAIL_ADDRESS=<yourmail@yandex.ru>

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - GITLAB_MATTERMOST_ENABLED=true
      - GITLAB_MATTERMOST_URL=""

      - SMTP_ENABLED=true
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.yandex.ru
      - SMTP_PORT=25
      - SMTP_USER=<yourmail@yandex.ru>
      - SMTP_PASS=<SMTP_PASSWORD>
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=true
      - IMAP_HOST=imap.yandex.ru
      - IMAP_PORT=993
      - IMAP_USER=<yourmail@yandex.ru>
      - IMAP_PASS=<IMAP_PASSWORD>
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - LDAP_ENABLED=true
      #- LDAP_LABEL=nas
      - LDAP_HOST=172.21.0.1
      - LDAP_PORT=389
      #- LDAP_METHOD=start_tls
      - LDAP_METHOD=plain
      - LDAP_UID=uid
      - LDAP_PASS=<LDAP_PASSWORD>
      #- LDAP_CA_FILE=
      # Default: false.
      #- LDAP_BLOCK_AUTO_CREATED_USERS=true
      - LDAP_BASE=ou=users,dc=nas,dc=nas
      - LDAP_BIND_DN=cn=readonly,dc=nas,dc=nas
      - LDAP_ACTIVE_DIRECTORY=false
      #- LDAP_USER_FILTER=(givenName=)
      - LDAP_USER_ATTRIBUTE_USERNAME=uid
      - LDAP_USER_FILTER=memberOf=cn=users_code,ou=groups,dc=nas,dc=nas
      - LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN=true
      - LDAP_VERIFY_SSL=false

      - OAUTH_ENABLED=false
      #- USERMAP_UID=$(id -u git)
      #- USERMAP_GID=$(id -g git)

      - GITLAB_REGISTRY_ENABLED=true
      - GITLAB_REGISTRY_HOST=docker-registry
      - GITLAB_REGISTRY_PORT=443
      - GITLAB_REGISTRY_API_URL=https://docker-registry.NAS.cloudns.cc/
      - GITLAB_REGISTRY_KEY_PATH=/docker-registry-certs/registry-auth.key
      - GITLAB_REGISTRY_CERT_PATH=/docker-registry-certs/registry-auth.crt
      - SSL_REGISTRY_CERT_PATH=/docker-registry-certs/registry-auth.crt
      - SSL_REGISTRY_KEY_PATH=/docker-registry-certs/registry-auth.key
      # - SSL_CERT_FILE=/docker-registry-certs/registry-auth.crt

# Internal registry. Doesn't used.
#  docker-registry:
#    restart: always
#    image: registry:2
#    volumes:
#      - /tank0/apps/docker-registry:/registry
#      - /tank0/apps/docker-registry/certs:/certs
#    environment:
#      - REGISTRY_LOG_LEVEL=info
#      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
#      - REGISTRY_AUTH_TOKEN_REALM=http://gitlab:80/jwt/auth
#      - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
#      - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
#      - REGISTRY_STORAGE_DELETE_ENABLED=true
#      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry-auth.pem
#      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry-auth.crt
#      - REGISTRY_HTTP_TLS_KEY=/certs/registry-auth.key
#    expose:
#      - 5000
#    networks:
#      - gitlab
#
