version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  emby:
    image: emby/embyserver:latest
    restart: always
    networks:
      - docker0
    expose:
      - 8096
    volumes:
      - /tank0/apps/media/emby/config:/config
      - /tank0/user_data:/mnt/share1
      #- /tank1/user_data:/mnt/share2
    environment:
      - GID=33
      - UID=33
      - GIDLIST=33,100
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=media.*
      - VIRTUAL_PORT=8096
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
