version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  beets:
    restart: always
    image: linuxserver/beets
    networks:
      - docker0
    expose:
      - 8337
    volumes:
      - /tank0/apps/media/beets/config:/config
      - /tank0/apps/media/beets/downloads:/downloads
      - /tank0/user_data/music:/music
    environment:
      - PGID=33
      - PUID=33
      - VIRTUAL_HOST=audio.*
      - VIRTUAL_PORT=8337
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
   
