version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  omeka:
    image: klokantech/omeka-docker 
    restart: always
    networks:
      - docker0
    expose:
      - 80
    volumes:
      - /tank0/user_data/music/Music:/music
    environment:
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=test.*
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

   
