version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  portainer:
    image: portainer/portainer-ce
    expose:
      - 9000
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - docker0
    volumes:
      - /tank0/apps/server_control/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.*
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
#      - LDAP_EXT_AUTH=true
#      - LDAP_EXT_ADD_GROUPS=(memberOf=cn=users_cloud,ou=groups,dc=nas,dc=nas)
