version: '3.3'

networks:
  docker0:
    external:
      name: docker0

services:
  emby:
    image: emby/embyserver:beta
    restart: always
    healthcheck:
      test: ['CMD', 'wget', '-q', 'http://localhost:8096/swagger', '-O', '/dev/null']
      interval: 5m
      timeout: 15s
      retries: 3
      # start_period: 1m
    networks:
      - docker0
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/renderD128
    expose:
      - 8096
      # HTTPS port.
      # - 8920
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
      - 1901:1901/udp
      - 35599:35599/udp
      - 56579:56579/udp
    volumes:
      - /tank0/apps/media/emby/config:/config
      - /tank0/apps/media/emby/backup:/backup
      - /tank0/user_data:/mnt/share1
      - /tank1/user_data:/mnt/share2
    tmpfs:
      #- /var/cache
      - /transcode:uid=33,gid=33
      - /tmp:uid=33,gid=33
      - /config/transcoding-temp:uid=33,gid=33
      - /config/cache:uid=33,gid=33
    environment:
      - GID=33
      - UID=33
      # 44 - video group.
      - GIDLIST=33,44,100,127
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=media.*
      - VIRTUAL_PORT=8096
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
