version: '2'

networks:
  docker0:
    external:
      name: docker0
  internal:

services:
  piwigo-db:
    image: mariadb
    restart: always
    networks:
      - internal
    volumes:
      - /tank0/apps/media/piwigo/data:/var/lib/mysql
    environment:
      - MYSQL_USER=piwigo
      - MYSQL_PASSWORD=changemetoo
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=piwigo

  piwigo:
    image: linuxserver/piwigo
    restart: always
    networks:
      - internal
      - docker0
    expose:
      - 80
    volumes:
      - /tank0/apps/media/piwigo:/config
      - /tank0/user_data/pictures:/pictures
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - piwigo-db
    environment:
      - PGID=33
      - PUID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=photo.*
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
