version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  netdata:
    image: netdata/netdata
    restart: always
    hostname: control.system.cloudns.cc
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - docker0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./hddtemp.conf:/etc/netdata/python.d/hddtemp.conf:ro
    environment:
      - VIRTUAL_HOST=control.*
      - VIRTUAL_PORT=19999
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
      - LDAP_EXT_AUTH=true
      - LDAP_EXT_ADD_GROUPS=(memberOf=cn=users_cloud,ou=groups,dc=nas,dc=nas)

