version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  ampache:
    image: ampache/ampache
    expose:
      - 80
    networks:
      - docker0
    volumes:
      - /tank0/user_data/music:/media:ro
      #- /tank0/apps/media/ampache/config:/var/www/config
      - /tank0/apps/media/ampache/db:/var/lib/mysql
      #- /tank0/apps/media/ampache/themes:/var/www/themes
    environment:
      - VIRTUAL_HOST=media.*
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

