version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  webdav:
    build: ./docker-webdav
    networks:
      - docker0
    expose:
      - 80
    volumes:
      - /tank0/user_data/:/data
      - /tank0/user_data/.uploads:/tmp/uploads
      - /tank0/apps/fs/webdav/logs:/log
    environment:
      - LDAP_SERVER=172.21.0.1
      - LDAP_PROTOCOL=ldap
      - LDAP_PORT=389
      # - LDAP_DOMAIN=test
      - LDAP_DN=ou=users,dc=nas,dc=nas
      - LDAP_FILTER=uid?sub?(&(objectClass=inetOrgPerson)(memberOf=cn=users_media,ou=groups,dc=nas,dc=nas))
      - LDAP_BIND_USER=cn=admin,dc=nas,dc=nas
      - LDAP_BIND_PASSWORD=<LDAP_PASSWORD>
      - LDAP_AUTH_MESSAGE=Please, enter your login and password
      - LDAP_OPEN_METHODS=none
      - CHOWN=0
      - MIN_DELETE_DEPTH=3
      - PGID=33
      - PUID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=files.*,dav.*
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
    restart: always
