#
# Library management service.
#

version: '2.1'

networks:
  docker0:
    external:
      name: docker0

services:
 calibre-web:
    restart: unless-stopped
    image: ghcr.io/linuxserver/calibre-web
    networks:
      - docker0
    expose:
      - 8083
    volumes:
      - /tank0/user_data/books/Books:/books:ro
      - /tank0/user_data/books/database:/data:rw
      - /tank0/apps/library/calibre-web/config:/config:rw
    environment:
      - VIRTUAL_HOST=library.*
      - VIRTUAL_PORT=8083
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
      - TZ=Europe/Moscow
      - PGID=33
      - PUID=33
      - DOCKER_MODS=linuxserver/calibre-web:calibre

