version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  flexget:
    image: szhajdu/docker-flexget
    restart: always
    expose:
      - 5050
    volumes:
      - /tank0/apps/flexget:/config:rw
      - /tank0/user_data/downloads:/downloads:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - docker0
    environment:
      - FG_WEBUI_PASSWD=flexget
      - FG_LOG_LEVEL=info
      - PUID=33
      - PGIDID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=download-files.*
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=5050
      - CERT_NAME=NAS.cloudns.cc
      - LDAP_EXT_AUTH=true
      - LDAP_EXT_ADD_GROUPS=(memberof=cn=users_cloud,ou=groups,dc=nas,dc=nas)
