version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  airsonic:
    image: linuxserver/airsonic
    restart: always
    networks:
      - docker0
    expose:
      - 4040
    volumes:
      - /tank0/apps/media/airsonic/config:/config
      - /tank0/apps/media/airsonic/playlists:/playlists
      - /tank0/apps/media/airsonic/podcasts:/podcasts
      - /tank0/apps/media/beets/downloads:/downloads
      - /tank0/user_data/music:/music
      #- </path/to/other media>:/media
    environment:
      - PGID=33
      - PUID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=audio.*
      - VIRTUAL_PORT=4040
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
      #- JAVA_OPTS=<options>
