version: '2'

networks:
  docker0:
    external:
      name: docker0
  internal:

services:
  lychee-db:
    image: mariadb
    restart: always
    networks:
      - internal
    volumes:
      - /tank0/apps/media/lychee/data:/var/lib/mysql
    environment:
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=changemetoo
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=lychee

  lychee:
    image: linuxserver/lychee
    restart: always
    depends_on:
      - lychee-db
    networks:
      - internal
      - docker0
    expose:
      - 80
    volumes:
      - /tank0/apps/media/lychee/config:/config
      - /tank0/user_data/pictures/Pictures:/Pictures
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=33
      - PUID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=photo.*
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

