version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  gallery:
    image: jwater7/responsive-photo-gallery
    restart: always
    networks:
      - docker0
    expose:
      - 3000
    volumes:
      - /tank0/apps/media/responsive/config:/config
      - /tank0/user_data/pictures/Pictures:/images
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DEFAULT_PASSWORD=admin
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=photo.*
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
