version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  oml:
    build: ./app
    volumes:
      # Main folder, needed for updating
      - /tank0/apps/cloud/nextcloud/html:/var/www/html
    networks:
      - docker0
    restart: always
    expose:
      - 9841
    environment:
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=test.*
      - VIRTUAL_PORT=9841
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

