version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  kodexplorer:
    image: yangxuan8282/kodexplorer
    restart: "always"
    networks:
      - docker0
    expose:
      - 80
    volumes:
      - "/tank0/apps/fs/kodexplorer/html:/var/www/html"
    environment:
      - PGID=33
      - PUID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=files.*
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

   
