version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  organizr:
    image: organizr/organizr
    restart: always
    expose:
      - 80
    volumes:
      - /tank0/apps/frontend/organizr:/config
    networks:
      - docker0
    environment:
      - PGID=33
      - PUID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=nas,www.*,NAS.cloudns.cc
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

