version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  sickrage:
    image: linuxserver/sickrage
    restart: always
    networks:
      - docker0
    expose:
      - 8081
    volumes:
      - /tank0/apps/media/sickrage/config:/config
      - /tank0/apps/media/sickrage/downloads:/downloads
      - /tank0/user_data/videos/Videos:/tv
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=996
      - PUID=1004
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=test.*
      - VIRTUAL_PORT=8081
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

   
