#
# Library management service.
#

version: '2.1'

networks:
  docker0:
    external:
      name: docker0

services:
  cops:
    restart: unless-stopped
    image: ghcr.io/linuxserver/cops
    container_name: cops
    networks:
      - docker0
    expose:
      - 80
    volumes:
      - /tank0/user_data/books/Books:/books
      - /tank0/user_data/books/database/metadata.db:/books/metadata.db
      - /tank0/apps/library/cops:/config:rw
    environment:
      - VIRTUAL_HOST=library-cops.*
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
      - TZ=Europe/Moscow
      - PGID=33
      - PUID=33
      - LDAP_EXT_AUTH=true
      - LDAP_EXT_ADD_GROUPS=(memberOf=cn=users_cloud,ou=groups,dc=nas,dc=nas)

