version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  subsonic:
    image: freenas/subsonic
    restart: always
    networks:
      - docker0
    expose:
      - 4040
    volumes:
      - /tank0/apps/media/subsonic:/subsonic
      - /tank0/apps/media/playlists:/playlists
      - /tank0/user_data/music:/music
      - /tank0/user_data/podcasts:/podcasts
    environment:
      - APP_GID=996
      - APP_UID=1004
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=media.*
      - VIRTUAL_PORT=4040
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

   
