version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  photoshow:
    image: linuxserver/photoshow
    restart: always
    networks:
      - docker0
    expose:
      - 80
    volumes:
      - /tank0/apps/media/photoshow/config:/config
      - /tank0/user_data/pictures/Pictures:/Pictures:ro
      - /tank0/user_data/pictures/thumbs:/Thumbs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=33
      - PUID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=photo.*
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
