version: '2'

networks:
  bareos:
  docker0:
    external:
      name: docker0

services:
  bareos-dir:
    #image: barcus/bareos-director:mysql_17 #(Bareos 17.2)
    #image: barcus/bareos-director:mysql_18 #(Bareos 18.2)
    image: barcus/bareos-director:pgsql_latest
    networks:
      - docker0
      - bareos
    volumes:
      - /tank0/apps/backup/bareos/var/bareos:/var/lib/bareos
      - /tank0/apps/backup/bareos/config:/etc/bareos
      - /tank0/apps/backup/bareos/log:/var/log
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_PASSWORD=ThisIsMySecretDBp4ssw0rd
      - DB_HOST=bareos-db
      - DB_PORT=5432
      - BAREOS_FD_HOST=bareos-fd
      - BAREOS_SD_HOST=bareos-sd
      - BAREOS_FD_PASSWORD=ThisIsMySecretFDp4ssw0rd
      - BAREOS_SD_PASSWORD=ThisIsMySecretSDp4ssw0rd
      - BAREOS_WEBUI_PASSWORD=ThisIsMySecretUIp4ssw0rd
      - SMTP_HOST=smtpd
      - ADMIN_MAIL=your@mail.address # Change me!
    depends_on:
      - bareos-db

  bareos-sd:
    #image: barcus/bareos-storage:17
    #image: barcus/bareos-storage:18
    image: barcus/bareos-storage:latest
    networks:
      - docker0
      - bareos
    ports:
      - 9103:9103
    volumes:
      - /tank0/apps/backup/bareos/config:/etc/bareos
      - /tank0/apps/backup/bareos/storage:/var/lib/bareos/storage
    environment:
      - BAREOS_SD_PASSWORD=ThisIsMySecretSDp4ssw0rd

  bareos-fd:
    #image: barcus/bareos-client:17
    #image: barcus/bareos-client:18
    image: barcus/bareos-client:latest
    networks:
      - bareos
    volumes:
      - /tank0/apps/backup/bareos/config:/etc/bareos
      - /tank0/apps/backup/bareos/var/bareos-director:/var/lib/bareos-director # (required for MyCatalog backup)
    environment:
      - BAREOS_FD_PASSWORD=ThisIsMySecretFDp4ssw0rd

  bareos-webui:
    #image: barcus/bareos-webui:17
    #image: barcus/bareos-webui:18
    image: barcus/bareos-webui:latest
    expose:
      - 80
    networks:
      - docker0
      - bareos
    links:
      - bareos-dir
    environment:
      - BAREOS_DIR_HOST=bareos-dir
    volumes:
      - /tank0/apps/backup/bareos/config/bareos-webui:/etc/bareos-webui
    environment:
    - VIRTUAL_HOST=backup.*
    - VIRTUAL_PORT=80
    - VIRTUAL_PROTO=http
    - CERT_NAME=NAS.cloudns.cc

  bareos-db:
    image: postgres:9.3
    networks:
      - bareos
    volumes:
      - /tank0/apps/backup/bareos/var/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ThisIsMySecretDBp4ssw0rd

  # bareos-db:
  #  image: mysql:5.6
  #  volumes:
  #    - <DB_DATA_PATH>:/var/lib/mysql
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=ThisIsMySecretDBp4ssw0rd

  smtpd:
    image: namshi/smtp
