version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  tmm:
    image: hurricane/tinymediamanager
    restart: always
    networks:
      - docker0
    expose:
      - 8080
      - 3389
    volumes:
      - /tank0/apps/media/tmm/config:/config
      - /tank0/user_data:/mnt
    environment:
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=media.*
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
