version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  netdata:
    image: netdata/netdata
    hostname: test.NAS.cloudns.cc
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - docker0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - VIRTUAL_HOST=test.*
      - VIRTUAL_PORT=19999
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc
