version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  cherrymusic:
    image: holizz/cherrymusic
    restart: always
    networks:
      - docker0
    expose:
      - 3000
    volumes:
      - /tank0/user_data/music:/music
      - /tank0/apps/media/cherry_music/config:/root/.local
    environment:
      - PGID=33
      - PUID=33
      - TZ=Europe/Moscow
      - VIRTUAL_HOST=audio.*
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=http
      - CERT_NAME=NAS.cloudns.cc

   
