version: '2'

networks:
  docker0:
    external:
      name: docker0

services:
  glances:
    image: nicolargo/glances
    restart: always
#    pid: "host"
    expose:
      - 61208
      - 61209
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - docker0
    environment:
     - VIRTUAL_HOST=test.*
     - VIRTUAL_PORT=61208
     - VIRTUAL_PROTO=http
     - CERT_NAME=NAS.cloudns.cc
     # --disable-wifi --disable-raid --enable-history --tree 
     #- GLANCES_OPT=['-w', '--fs-free-spacei', '--username', '--password']

